#!/bin/sh -xe

. CI/travis/lib.sh

brew_install_if_not_exists cmake doxygen libusb libxml2 swig curl python mono

cd $TRAVIS_BUILD_DIR
git clone https://github.com/analogdevicesinc/libiio
mkdir -p libiio/build
cd libiio/build
cmake ..
make
sudo make install

cd ${TRAVIS_BUILD_DIR}
git clone --branch v0.3.5 --depth 1 https://github.com/google/glog
mkdir -p glog/build && cd glog/build
cmake ..
make
sudo make install

#wget http://swdownloads.analog.com/cse/travis_builds/${LIBIIO_BRANCH}_latest_libiio${LDIST}.pkg
#sudo installer -pkg ${LIBIIO_BRANCH}_latest_libiio${LDIST}.pkg -target /

pip3 install wheel
