#!/bin/sh -e

TOP_DIR=$(pwd)

mkdir -p build
mkdir -p build_tar

cd build
cmake -DOSX_PACKAGE=ON -DENABLE_TOOLS=ON -DENABLE_PYTHON=ON -DENABLE_CSHARP=ON -DENABLE_LOG=ON -DBUILD_EXAMPLES=ON ..
make
ls

python3 setup.py sdist bdist_wheel
ls dist

cd ${TOP_DIR}/build_tar
cmake -DOSX_PACKAGE=OFF -DENABLE_PACKAGING=ON -DENABLE_PYTHON=ON -DENABLE_CSHARP=ON -DENABLE_TOOLS=ON -DENABLE_LOG=ON -DBUILD_EXAMPLES=ON ..
make && make package
ls
