#!/bin/sh -e

TOP_DIR=$(pwd)
LIBIIO_VERSION=libiio-v0

set -x

# Note: not installing 'mono', it comes with Azure images,
# but it doesn't look it's installed with Homebrew
brew install cmake doxygen libusb libxml2 swig curl python
# libiio deps
brew install doxygen libusb libxml2 ncurses cdk libserialport sphinx-doc pkg-config
pip3 install sphinx

pip3 install wheel twine build virtualenv

# Install glog
echo "Building glog"
cd ${TOP_DIR}
git clone --branch v0.4.0 --depth 1 https://github.com/google/glog
mkdir -p glog/build_0_4_0 && cd glog/build_0_4_0
cmake ..
make
sudo make install

# Install libiio
echo "Building libiio - version $LIBIIO_VERSION"
cd ${TOP_DIR}
git clone https://github.com/analogdevicesinc/libiio.git -b $LIBIIO_VERSION libiio
mkdir ./libiio/build && cd ./libiio/build
cmake ../
make
sudo make install 

