# support creating some basic binpkgs via `make package`

set(CPACK_SET_DESTDIR ON)
set(CPACK_GENERATOR TGZ)

set(CPACK_PACKAGE_VERSION_MAJOR ${LIBM2K_VERSION_MAJOR})
set(CPACK_PACKAGE_VERSION_MINOR ${LIBM2K_VERSION_MINOR})
set(CPACK_PACKAGE_VERSION_PATCH g${LIBM2K_VERSION_GIT})
set(CPACK_BUNDLE_NAME libm2k)
set(CPACK_PACKAGE_VERSION ${PROJECT_VERSION})

include(CPack)
