if (@ENABLE_LOG@)
    include(CMakeFindDependencyMacro)
    find_dependency(glog)
endif()
set(@PROJECT_NAME@_VERSION_GIT @LIBM2K_VERSION_GIT@)
include("${CMAKE_CURRENT_LIST_DIR}/@PROJECT_NAME@Targets.cmake")
